### ISSUE TITLE
Consultation on the center sub-aperture image

### ISSUE THREAD

**Issue by zhangyukuin** [MaximilianStaab/mDFF#1]
Hi Staab,
Thank you for sharing this dataset. I  downloaded the original focalstacks. However, I didn't find the center sub-aperture image.

![image](https://user-images.githubusercontent.com/43198769/57819100-7cebe400-77b9-11e9-82b0-5ceb8e57da80.png)
I want to know if the first column of the result graph in the paper is one of the focus stacks or a center sub-aperture image?

**Comment by MaximilianStaab** [comment]
Hi zhangyukuin,
you're welcome! Cool that the dataset comes in handy for someone else now.
Subapertures are intermediate products when shooting pictures with light field cameras.
However, this dataset was created with the main RGB camera and the depth sensor of the Lenovo Phab2 Pro only. These two sensors work like regular cameras and produce single images. The Phab2 has no light field camera.
Therefore, all images from my dataset - including the ones depicted in the paper - are part of the focal stacks. IIRC, the figures in the paper are cropped versions which match the image section of the depth maps, though. That's why there exist original (raw) and cropped versions which might have misled you into thinking there were subaperture images.
