### ISSUE TITLE
Speed of running the alignment script 

### ISSUE THREAD

**Issue by nancibles** [MaximilianStaab/mDFF#2]
Thanks for sharing your code and dataset, it's definitely come in handy for me and I'm trying to adapt it for my project. I'm just wondering how long it takes for you to run the align_focal_stacks script using those criteria with the data you provided in the focalstacks folder? It takes me quite a while to complete one focal stack with the default settings and I wanted to see if maybe I'm doing something wrong.

**Comment by MaximilianStaab** [comment]
Hi nancibles,
the align_focal_stacks script basically comes down to the not-too-complex OpenCV-functions `cv2.findTransformECC()` and `cv2.warpAffine()` which get called for each image. I don't really remember how long it took to run the script for the whole dataset, but since the OpenCV-library is written in a highly efficient way in C++, it shouldn't take so long - especially for one single stack which contains 10 images and should be processed nearly instantaneously. I think the whole dataset didn't take longer than a few minutes on consumer hardware.
