### ISSUE TITLE
Depth Map Projection and Alignment

### ISSUE THREAD

**Issue by nancibles** [MaximilianStaab/mDFF#3]
Thanks again for sharing this code and data -- it has been very helpful to me. I'm still trying to work out some details in my project which will make use of the DDFFNet and I was hoping you might be able to help. I'm just curious if your project_pointcloud script was also for the purpose of re-aligning the depth map so that it matches the camera image. I understand that in the DDFF dataset, the stereo calibration had to be done but I was not sure if it was the depth map that also needs to be rectified -- and that is what project_pointclouds.py does? Or is it simply to convert the Phab Pro's raw data into a 2D depth image without alignment, and the MATLAB calibration toolbox takes care of rectifying both the depth map and the RGB image?

**Comment by MaximilianStaab** [comment]
Hi nancibles, it is nice to hear that this is actually helpful for someone else! Since that was also the purpose of publishing, it makes sense for me to make clear, how it is working. It has been a while for me to work with the scripts and the calibration matter is indeed a bit confusing, but I'll try my best to remember.

The two scripts you mention fulfill two different purposes: project_pointclouds.py does the actual point cloud to depth map conversion and the registration with the color images while align_focal_stacks.py just deals with the re-alignment of the color images of each focal stack.

Due to the physical properties of the camera's lens system, shifting the focus backwards is accompanied by a slight increase in field of view (as if the view gets zoomed out a bit). Since the only attribute changing within a focal stack should be the focus of course, the change in field of view had to be compensated - that is what align_focal_stacks.py is for. Sure, applying a simple affine transformation is not physically correct, but it does the trick well enough in this case. The script gradually "zooms into" the last n-1 frames, so to say, and brings the visible objects to the same scale as they are in the first frame of the processed focal stack. Afterwards the frames get cropped to be the same resolution again and now depict the same objects under the same perspective.

On the other hand, project_pointclouds.py projects the pointclouds into a 2D-depth map, scales it up, and introduces the same optical distortion properties of the color camera. This is done with the following steps:

1. At first, all point clouds get projected back to a 2D-plane, but since we want the cloud projected "as seen from" the color camera instead of the IR-camera, from which the clouds were recorded and which sits beneath the IR-camera, we first rotate and translate the point clouds with the extrinsical rotation and translation vectors between RGB- and IR-camera, we calculated with the Matlab toolbox. This happens in the function project_pointcloud.
2. Next, since multiple point clouds per focal stack scene were recorded to reduce outliers and noise, we now fuse the depth maps belonging to the same scene by using the median value of each pixel. This happens directly inside the function __process_point_cloud_folder.
3. The resulting depth maps are very small compared to the high resolution RGB-frames. Furthermore, the lens distortion of the IR-camera in fact got eliminated during step 1, but the RGB-frames themselves are still optically distorted according to the RGB-camera's lens properties. In the function fuse_rgb_depth, a new, upscaled version of the depth maps are created by re-sampling the maps with respect to the RGB-camera's intrinsic parameters.

The second script also does some other things like clipping the depth values and so on.

I hope that I got everything right and that this will enable you to fully understand the preprocessing scripts and bring your project to a successful end!
Cheers!

**Comment by nancibles** [comment]
Thank you once again for your quick reply, it has made things a lot clearer for me. However, I have not been able to produce a reprojected pointcloud when using my depth sensor so if it's not too much trouble, I was also wondering a few more things. 

For the pointclouds that you have in your dataset, they are quite low resolution. Is this because the depth sensor you used for the pointcloud is a low resolution sensor or is there a reason you chose to use such a low resolution? 

I also was wondering about the matrix you have for the intrinsics -- are k1, k2, p1, p2, k3 the parameters from the distortion matrix, kc, obtained from the MATLAB Calibration Toolbox? Or are they calculated differently after the MATLAB calibration is done?

Thanks again, your help means a lot to me and I hope I'll have something to share with you soon.

**Comment by hazirbas** [comment]
Hi,
We stick to the toolbox provided in the paper for calibration parameters. We do not have any undistortion for the depth camera itself. Main reason of the low resolution is because of the output LF resolution and its registration error onto the depth map, i.e., placement of the rgb-d camera on the LF sensor.

**Comment by MaximilianStaab** [comment]
Hey,
just to address your specific questions:

The point clouds are indeed as raw as we obtained them from the sensor. We didn't modify them in any way, so the sensor has a low resolution, yes. Furthermore, a lot of points per scene are lost where the IR-rays reach too far into the background or hit highly reflective or very dark surfaces or hit surfaces tangentially in a shallow angle, so that the rays don't get reflected back into the sensor resulting in "no data"-areas.

All camera parameters excluding the extrinsic parameters were queried from the Tango-API - we didn't calculate them by ourselves.
If you can't find out your sensor's internal parameters, you will have to do an intrinsic calibration yourself. Keep in mind that there are two different sets of parameters: The intrinsic camera matrix consisting of fx, fy, cx and cy as well as the lens distortion parameters k1, k2, p1, p2, k3 consisting of radial (k) and tangential (p) parameters, which can be used with the Brown–Conrady distortion model:
https://en.wikipedia.org/wiki/Distortion_(optics)#Software_correction
To calculate the parameters you can either use the Matlab-toolbox, or something else like, for example, OpenCV:
https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html (C++)
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html (Python)
These links should also give you more detail about this topic. Typically, you first need to calculate the intrinsics before you can calculate the extrinsics.
